title: Magit
author: Jonas Bernoulli
email: jonas@bernoul.li
url: https://magit.vc

baseurl: ""
permalink: /:year/:month/:day/:title/index.html
markdown: kramdown
keep_files:
  - elpa
  - img
  - manual
  - screenshots
  - screencasts
  - stats
exclude:
  - config.mk
  - Makefile

relnotes: https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes
rawgithub: https://raw.githubusercontent.com/magit
